
version: '3'
services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
  web:
    container_name:  django_web
    build: .
    image: python:3
    command: python3 manage.py runserver 0.0.0.0:8000
#    volumes:
#      - $HOME/Yandex_Pr/Sprint_1/SQL/new_admin_panel_sprint_1/02_movies_admin:/code/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

