version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data

  django:
    container_name: django
    build:
      context: .
    volumes:
      - static_data:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - static_data:/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_data:

