version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data

  django:
    container_name: django
    build:
      context: .
    volumes:
      - static_data:/app/static
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - static_data:/static
    ports:
      - "80:80"
    depends_on:
      - django

  elasticsearch:
    container_name: elastic_search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    env_file:
      - .env
    image: elasticsearch:7.17.1
    ports:
      - 9200:9200
    depends_on:
      - postgres


volumes:
  static_data:


